name: Bloguee
description: Internal sharing network for business.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.3
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  flutter_secure_storage: ^9.0.0
  badges: ^3.1.2
  flutter_markdown: ^0.6.18+2
  dio: ^5.3.4
  file_picker: ^6.1.1
  typed_data: ^1.3.2
  html: ^0.15.4
  flutter_snake_navigationbar: ^0.6.1
  flutter_native_splash: 1.2.0
  syncfusion_flutter_pdfviewer: ^23.2.6
  advance_pdf_viewer: ^2.0.1
  shimmer: ^3.0.0
  url_launcher: ^6.2.1
  path_provider: ^2.1.1
  universal_platform: ^1.0.0+1
  flutter_config: ^2.0.2
  envied: ^0.5.2



flutter_native_splash:
  color: "#ffffff"
  image: "assets/app/splash.png"
  android: true
  ios: true

# dart run flutter_native_splash:create



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
  - assets/images/branco.png
  - assets/images/preto.png


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
        - weight: 500



assets:
  - .env